// seeds/rubros.js — Catálogo de rubros para la Demo Version
// Compatible con Node.js (require) y browser (window.RUBROS via <script>)

const RUBROS = [
  // ─── TIPO: mesas (restaurantes con mesas) ───────────────────────────────
  {
    slug: 'taqueria',
    nombre: 'Taquería',
    icono: '🌮',
    descripcion: 'Restaurante con mesas y mostrador',
    color: '#365322',
    colorDark: '#243718',
    colorLight: '#4a6b30',
    colorCream: '#FDF8D0',
    tipo: 'mesas',
    tabs: ['mesas','mostrador','cocina','caja','inventario','menu','reportes','admin'],
    mesasCount: 8,
    menu: [
      { id:1, nombre:'Taco de birria',  precio:45, emoji:'🌮', invId:1, unidad:'u' },
      { id:2, nombre:'Taco al pastor',  precio:35, emoji:'🌮', invId:2, unidad:'u' },
      { id:3, nombre:'Quesadilla',      precio:30, emoji:'🫓', invId:3, unidad:'u' },
      { id:4, nombre:'Birriamen',       precio:65, emoji:'🍜', invId:1, unidad:'u' },
      { id:5, nombre:'Refresco',        precio:15, emoji:'🥤', invId:4, unidad:'u' },
      { id:6, nombre:'Agua de horchata',precio:12, emoji:'🥛', invId:5, unidad:'u' },
    ],
    inventario: [
      { id:1, nombre:'Carne birria',  stock:11,  min:4.5, unidad:'lb' },
      { id:2, nombre:'Carne pastor',  stock:9,  min:4.5, unidad:'lb' },
      { id:3, nombre:'Tortillas',     stock:10, min:3, unidad:'paquete' },
      { id:4, nombre:'Refrescos',     stock:24, min:6, unidad:'u' },
      { id:5, nombre:'Horchata',      stock:8,  min:2, unidad:'u' },
    ],
  },
  {
    slug: 'cafeteria',
    nombre: 'Cafetería',
    icono: '☕',
    descripcion: 'Café y postres con mesas',
    color: '#5D3A1F',
    colorDark: '#3a2412',
    colorLight: '#7a5030',
    colorCream: '#f5e8d0',
    tipo: 'mesas',
    tabs: ['mesas','mostrador','cocina','caja','inventario','menu','reportes','admin'],
    mesasCount: 10,
    menu: [
      { id:1, nombre:'Americano',        precio:25, emoji:'☕', invId:1, unidad:'u' },
      { id:2, nombre:'Cappuccino',        precio:35, emoji:'☕', invId:1, unidad:'u' },
      { id:3, nombre:'Latte',            precio:40, emoji:'🥛', invId:1, unidad:'u' },
      { id:4, nombre:'Pastel de chocolate', precio:45, emoji:'🎂', invId:2, unidad:'u' },
      { id:5, nombre:'Croissant',        precio:25, emoji:'🥐', invId:3, unidad:'u' },
      { id:6, nombre:'Cheesecake',       precio:50, emoji:'🍰', invId:4, unidad:'u' },
    ],
    inventario: [
      { id:1, nombre:'Café molido',    stock:6.5,  min:2, unidad:'lb' },
      { id:2, nombre:'Pastel chocolate', stock:12, min:3, unidad:'u' },
      { id:3, nombre:'Croissants',     stock:20, min:5, unidad:'u' },
      { id:4, nombre:'Cheesecakes',    stock:8,  min:2, unidad:'u' },
    ],
  },
  {
    slug: 'pizzeria',
    nombre: 'Pizzería',
    icono: '🍕',
    descripcion: 'Pizzas y pasta con mesas',
    color: '#8B2418',
    colorDark: '#5a1610',
    colorLight: '#a83a2c',
    colorCream: '#fbe8c8',
    tipo: 'mesas',
    tabs: ['mesas','mostrador','cocina','caja','inventario','menu','reportes','admin'],
    mesasCount: 12,
    menu: [
      { id:1, nombre:'Pizza Margherita', precio:120, emoji:'🍕', invId:1, unidad:'u' },
      { id:2, nombre:'Pizza Pepperoni',  precio:145, emoji:'🍕', invId:2, unidad:'u' },
      { id:3, nombre:'Pizza Hawaiana',   precio:135, emoji:'🍕', invId:3, unidad:'u' },
      { id:4, nombre:'Pasta Carbonara',  precio:95,  emoji:'🍝', invId:4, unidad:'u' },
      { id:5, nombre:'Refresco 500ml',   precio:20,  emoji:'🥤', invId:5, unidad:'u' },
    ],
    inventario: [
      { id:1, nombre:'Masa pizza',      stock:15, min:5, unidad:'u' },
      { id:2, nombre:'Pepperoni',       stock:4.5,  min:2, unidad:'lb' },
      { id:3, nombre:'Piña (lata)',      stock:10, min:3, unidad:'u' },
      { id:4, nombre:'Pasta seca',      stock:6.5,  min:2, unidad:'lb' },
      { id:5, nombre:'Refrescos',       stock:36, min:12, unidad:'u' },
    ],
  },
  {
    slug: 'pupuseria',
    nombre: 'Pupusería',
    icono: '🫓',
    descripcion: 'Pupusas y comida típica con mesas',
    color: '#1F5F4A',
    colorDark: '#0e3a2c',
    colorLight: '#2e7a60',
    colorCream: '#fdf3d8',
    tipo: 'mesas',
    tabs: ['mesas','mostrador','cocina','caja','inventario','menu','reportes','admin'],
    mesasCount: 8,
    menu: [
      { id:1, nombre:'Pupusa de chicharrón', precio:12, emoji:'🫓', invId:1, unidad:'u' },
      { id:2, nombre:'Pupusa de queso',       precio:10, emoji:'🫓', invId:1, unidad:'u' },
      { id:3, nombre:'Pupusa revuelta',       precio:14, emoji:'🫓', invId:1, unidad:'u' },
      { id:4, nombre:'Atol de elote',         precio:15, emoji:'🥛', invId:2, unidad:'u' },
      { id:5, nombre:'Horchata',             precio:12, emoji:'🥛', invId:3, unidad:'u' },
    ],
    inventario: [
      { id:1, nombre:'Masa de maíz',   stock:22, min:6.5, unidad:'lb' },
      { id:2, nombre:'Elote dulce',    stock:20, min:5, unidad:'u' },
      { id:3, nombre:'Horchata',       stock:8,  min:2, unidad:'u' },
    ],
  },
  {
    slug: 'marisqueria',
    nombre: 'Marisquería',
    icono: '🦐',
    descripcion: 'Mariscos frescos con mesas',
    color: '#1F4A6B',
    colorDark: '#0e2a40',
    colorLight: '#2e6090',
    colorCream: '#f0eddc',
    tipo: 'mesas',
    tabs: ['mesas','mostrador','cocina','caja','inventario','menu','reportes','admin'],
    mesasCount: 10,
    menu: [
      { id:1, nombre:'Cóctel de camarón', precio:95,  emoji:'🦐', invId:1, unidad:'u' },
      { id:2, nombre:'Ceviche mixto',     precio:110, emoji:'🐟', invId:2, unidad:'u' },
      { id:3, nombre:'Camarón al ajillo', precio:130, emoji:'🦐', invId:1, unidad:'u' },
      { id:4, nombre:'Filete de pescado', precio:120, emoji:'🐟', invId:2, unidad:'u' },
      { id:5, nombre:'Cerveza',           precio:30,  emoji:'🍺', invId:3, unidad:'u' },
    ],
    inventario: [
      { id:1, nombre:'Camarón fresco', stock:4.5,  min:2, unidad:'lb' },
      { id:2, nombre:'Filete pescado', stock:6.5,  min:2, unidad:'lb' },
      { id:3, nombre:'Cervezas',       stock:24, min:6, unidad:'u' },
    ],
  },
  {
    slug: 'creperia',
    nombre: 'Crepería',
    icono: '🥞',
    descripcion: 'Crepas dulces y saladas con mesas',
    color: '#7A4F1F',
    colorDark: '#4a3012',
    colorLight: '#9a6a35',
    colorCream: '#fff5d8',
    tipo: 'mesas',
    tabs: ['mesas','mostrador','cocina','caja','inventario','menu','reportes','admin'],
    mesasCount: 8,
    menu: [
      { id:1, nombre:'Crepa Nutella',    precio:55, emoji:'🥞', invId:1, unidad:'u' },
      { id:2, nombre:'Crepa jamón queso',precio:60, emoji:'🥞', invId:2, unidad:'u' },
      { id:3, nombre:'Crepa frutas',     precio:65, emoji:'🍓', invId:3, unidad:'u' },
      { id:4, nombre:'Jugo natural',     precio:25, emoji:'🥤', invId:4, unidad:'u' },
      { id:5, nombre:'Batido fresa',     precio:40, emoji:'🥤', invId:5, unidad:'u' },
    ],
    inventario: [
      { id:1, nombre:'Nutella',         stock:11,  min:2, unidad:'lb' },
      { id:2, nombre:'Jamón/queso',     stock:4.5,  min:2, unidad:'lb' },
      { id:3, nombre:'Mix frutas',      stock:6.5,  min:2, unidad:'lb' },
      { id:4, nombre:'Jugos',           stock:12, min:3, unidad:'u' },
      { id:5, nombre:'Fresa congelada', stock:4.5,  min:2, unidad:'lb' },
    ],
  },

  // ─── TIPO: mostrador (comercios por unidad sin mesas) ────────────────────
  {
    slug: 'heladeria',
    nombre: 'Heladería',
    icono: '🍦',
    descripcion: 'Helados y paletas para llevar',
    color: '#A8508A',
    colorDark: '#6b2f5a',
    colorLight: '#c070a8',
    colorCream: '#fbeaf2',
    tipo: 'mostrador',
    tabs: ['mostrador','cocina','caja','inventario','menu','reportes','admin'],
    mesasCount: 0,
    menu: [
      { id:1, nombre:'Bola de helado',   precio:18, emoji:'🍦', invId:1, unidad:'u' },
      { id:2, nombre:'Copa 2 bolas',     precio:30, emoji:'🍨', invId:1, unidad:'u' },
      { id:3, nombre:'Paleta cremosa',   precio:20, emoji:'🍡', invId:2, unidad:'u' },
      { id:4, nombre:'Malteada',         precio:45, emoji:'🥤', invId:3, unidad:'u' },
      { id:5, nombre:'Sundae',           precio:55, emoji:'🍧', invId:1, unidad:'u' },
    ],
    inventario: [
      { id:1, nombre:'Helado (litro)',  stock:15, min:4, unidad:'u' },
      { id:2, nombre:'Paletas',         stock:40, min:10, unidad:'u' },
      { id:3, nombre:'Leche (litro)',   stock:8,  min:2, unidad:'u' },
    ],
  },
  {
    slug: 'dulceria',
    nombre: 'Dulcería',
    icono: '🍬',
    descripcion: 'Dulces, chocolates y golosinas',
    color: '#C4445A',
    colorDark: '#7a2a3a',
    colorLight: '#d86070',
    colorCream: '#fde8ee',
    tipo: 'mostrador',
    tabs: ['mostrador','caja','inventario','menu','reportes','admin'],
    mesasCount: 0,
    menu: [
      { id:1, nombre:'Dulce de tamarindo', precio:5,  emoji:'🍬', invId:1, unidad:'u' },
      { id:2, nombre:'Chocolate relleno',  precio:12, emoji:'🍫', invId:2, unidad:'u' },
      { id:3, nombre:'Gomitas surtidas',   precio:8,  emoji:'🍡', invId:3, unidad:'u' },
      { id:4, nombre:'Paleta de mango',    precio:10, emoji:'🍭', invId:4, unidad:'u' },
      { id:5, nombre:'Bolsa mix (100g)',   precio:20, emoji:'🛍️', invId:5, unidad:'u' },
    ],
    inventario: [
      { id:1, nombre:'Tamarindos',      stock:100, min:20, unidad:'u' },
      { id:2, nombre:'Chocolates',      stock:50,  min:10, unidad:'u' },
      { id:3, nombre:'Gomitas (lb)',    stock:11,   min:2,  unidad:'lb' },
      { id:4, nombre:'Paletas mango',   stock:60,  min:15, unidad:'u' },
      { id:5, nombre:'Surtido dulces',  stock:6.5,   min:2,  unidad:'lb' },
    ],
  },
  {
    slug: 'panaderia',
    nombre: 'Panadería',
    icono: '🥖',
    descripcion: 'Pan artesanal, pasteles y repostería',
    color: '#6B4423',
    colorDark: '#42290f',
    colorLight: '#8a5c35',
    colorCream: '#fcedd0',
    tipo: 'mostrador',
    tabs: ['mostrador','caja','inventario','menu','reportes','admin'],
    mesasCount: 0,
    menu: [
      { id:1, nombre:'Baguette',           precio:15, emoji:'🥖', invId:1, unidad:'u' },
      { id:2, nombre:'Pan dulce (pieza)',  precio:5,  emoji:'🥐', invId:2, unidad:'u' },
      { id:3, nombre:'Cuernito',           precio:10, emoji:'🥐', invId:3, unidad:'u' },
      { id:4, nombre:'Pastel chocolate',   precio:80, emoji:'🎂', invId:4, unidad:'u' },
      { id:5, nombre:'Galletas (bolsa)',   precio:20, emoji:'🍪', invId:5, unidad:'u' },
      { id:6, nombre:'Rosca de reyes',     precio:120,emoji:'🍩', invId:6, unidad:'u' },
    ],
    inventario: [
      { id:1, nombre:'Baguettes',      stock:20, min:5,  unidad:'u' },
      { id:2, nombre:'Pan dulce',      stock:60, min:15, unidad:'u' },
      { id:3, nombre:'Cuernitos',      stock:30, min:8,  unidad:'u' },
      { id:4, nombre:'Pasteles',       stock:5,  min:2,  unidad:'u' },
      { id:5, nombre:'Galletas bolsa', stock:25, min:5,  unidad:'u' },
      { id:6, nombre:'Roscas',         stock:4,  min:1,  unidad:'u' },
    ],
  },
  {
    slug: 'libreria',
    nombre: 'Librería',
    icono: '📚',
    descripcion: 'Libros, útiles y papelería fina',
    color: '#284B6E',
    colorDark: '#152d44',
    colorLight: '#3a6090',
    colorCream: '#f0e8d8',
    tipo: 'mostrador',
    tabs: ['mostrador','caja','inventario','menu','reportes','admin'],
    mesasCount: 0,
    menu: [
      { id:1, nombre:'Cuaderno universitario', precio:25, emoji:'📓', invId:1, unidad:'u' },
      { id:2, nombre:'Bolígrafo azul',          precio:5,  emoji:'🖊️', invId:2, unidad:'u' },
      { id:3, nombre:'Lápiz HB',               precio:3,  emoji:'✏️', invId:3, unidad:'u' },
      { id:4, nombre:'Block de hojas',          precio:15, emoji:'📄', invId:4, unidad:'u' },
      { id:5, nombre:'Pegamento',               precio:12, emoji:'🔑', invId:5, unidad:'u' },
      { id:6, nombre:'Mochila básica',          precio:150,emoji:'🎒', invId:6, unidad:'u' },
    ],
    inventario: [
      { id:1, nombre:'Cuadernos univ.',  stock:40, min:10, unidad:'u' },
      { id:2, nombre:'Bolígrafos',       stock:100,min:20, unidad:'u' },
      { id:3, nombre:'Lápices',         stock:80, min:20, unidad:'u' },
      { id:4, nombre:'Blocks hojas',    stock:25, min:5,  unidad:'u' },
      { id:5, nombre:'Pegamentos',      stock:30, min:8,  unidad:'u' },
      { id:6, nombre:'Mochilas',        stock:10, min:3,  unidad:'u' },
    ],
  },
  {
    slug: 'floreria',
    nombre: 'Florería',
    icono: '🌷',
    descripcion: 'Flores naturales y arreglos florales',
    color: '#7A3A60',
    colorDark: '#4a2038',
    colorLight: '#9a5080',
    colorCream: '#fbecf2',
    tipo: 'mostrador',
    tabs: ['mostrador','caja','inventario','menu','reportes','admin'],
    mesasCount: 0,
    menu: [
      { id:1, nombre:'Ramo de rosas (12)', precio:150, emoji:'🌹', invId:1, unidad:'u' },
      { id:2, nombre:'Girasoles (5)',       precio:80,  emoji:'🌻', invId:2, unidad:'u' },
      { id:3, nombre:'Arreglo especial',    precio:250, emoji:'💐', invId:3, unidad:'u' },
      { id:4, nombre:'Orquídea en maceta', precio:180, emoji:'🌸', invId:4, unidad:'u' },
      { id:5, nombre:'Tulipanes (6)',       precio:120, emoji:'🌷', invId:5, unidad:'u' },
    ],
    inventario: [
      { id:1, nombre:'Rosas rojas',    stock:60, min:12, unidad:'u' },
      { id:2, nombre:'Girasoles',      stock:30, min:5,  unidad:'u' },
      { id:3, nombre:'Mix flores',     stock:5,  min:2,  unidad:'u' },
      { id:4, nombre:'Orquídeas',      stock:8,  min:2,  unidad:'u' },
      { id:5, nombre:'Tulipanes',      stock:36, min:6,  unidad:'u' },
    ],
  },
  {
    slug: 'boutique',
    nombre: 'Boutique ropa',
    icono: '👗',
    descripcion: 'Ropa y accesorios de moda',
    color: '#2A2F4A',
    colorDark: '#15192d',
    colorLight: '#404868',
    colorCream: '#f5ecd8',
    tipo: 'mostrador',
    tabs: ['mostrador','caja','inventario','menu','reportes','admin'],
    mesasCount: 0,
    menu: [
      { id:1, nombre:'Blusa casual',   precio:180, emoji:'👚', invId:1, unidad:'u' },
      { id:2, nombre:'Pantalón jeans', precio:320, emoji:'👖', invId:2, unidad:'u' },
      { id:3, nombre:'Vestido floral', precio:280, emoji:'👗', invId:3, unidad:'u' },
      { id:4, nombre:'Cinturón cuero', precio:95,  emoji:'👜', invId:4, unidad:'u' },
      { id:5, nombre:'Bufanda',        precio:75,  emoji:'🧣', invId:5, unidad:'u' },
    ],
    inventario: [
      { id:1, nombre:'Blusas casual',   stock:20, min:5,  unidad:'u' },
      { id:2, nombre:'Pantalones',      stock:15, min:3,  unidad:'u' },
      { id:3, nombre:'Vestidos',        stock:12, min:3,  unidad:'u' },
      { id:4, nombre:'Cinturones',      stock:10, min:2,  unidad:'u' },
      { id:5, nombre:'Bufandas',        stock:15, min:3,  unidad:'u' },
    ],
  },
  {
    slug: 'papeleria',
    nombre: 'Papelería',
    icono: '✏️',
    descripcion: 'Útiles escolares e impresiones',
    color: '#3A6E5C',
    colorDark: '#1f4234',
    colorLight: '#508c78',
    colorCream: '#fbf6e0',
    tipo: 'mostrador',
    tabs: ['mostrador','caja','inventario','menu','reportes','admin'],
    mesasCount: 0,
    menu: [
      { id:1, nombre:'Fotocopia (c/u)',    precio:0.5, emoji:'📄', invId:1, unidad:'u' },
      { id:2, nombre:'Impresión color',   precio:3,   emoji:'🖨️', invId:1, unidad:'u' },
      { id:3, nombre:'Folder Manila',     precio:5,   emoji:'📁', invId:2, unidad:'u' },
      { id:4, nombre:'Caja crayones 24',  precio:30,  emoji:'🖍️', invId:3, unidad:'u' },
      { id:5, nombre:'Regla 30cm',        precio:8,   emoji:'📏', invId:4, unidad:'u' },
      { id:6, nombre:'Tijeras',           precio:15,  emoji:'✂️', invId:5, unidad:'u' },
    ],
    inventario: [
      { id:1, nombre:'Papel bond (resma)',stock:10, min:2,  unidad:'u' },
      { id:2, nombre:'Folders manila',   stock:50, min:10, unidad:'u' },
      { id:3, nombre:'Crayones 24',      stock:20, min:5,  unidad:'u' },
      { id:4, nombre:'Reglas 30cm',      stock:30, min:8,  unidad:'u' },
      { id:5, nombre:'Tijeras',          stock:15, min:4,  unidad:'u' },
    ],
  },
  {
    slug: 'farmacia',
    nombre: 'Farmacia',
    icono: '💊',
    descripcion: 'Medicamentos y artículos de salud',
    color: '#1F6E5A',
    colorDark: '#0e4234',
    colorLight: '#2e8c70',
    colorCream: '#eaf4f0',
    tipo: 'mostrador',
    tabs: ['mostrador','caja','inventario','menu','reportes','admin'],
    mesasCount: 0,
    menu: [
      { id:1, nombre:'Paracetamol 500mg (cja)', precio:25, emoji:'💊', invId:1, unidad:'u' },
      { id:2, nombre:'Ibuprofeno 400mg (cja)',  precio:30, emoji:'💊', invId:2, unidad:'u' },
      { id:3, nombre:'Alcohol 250ml',           precio:15, emoji:'🧴', invId:3, unidad:'u' },
      { id:4, nombre:'Curitas (caja)',           precio:20, emoji:'🩹', invId:4, unidad:'u' },
      { id:5, nombre:'Termómetro digital',      precio:80, emoji:'🌡️', invId:5, unidad:'u' },
      { id:6, nombre:'Vitamina C (30 tabs)',     precio:35, emoji:'🍊', invId:6, unidad:'u' },
    ],
    inventario: [
      { id:1, nombre:'Paracetamol 500mg', stock:30, min:8,  unidad:'u' },
      { id:2, nombre:'Ibuprofeno 400mg',  stock:25, min:6,  unidad:'u' },
      { id:3, nombre:'Alcohol 250ml',     stock:20, min:5,  unidad:'u' },
      { id:4, nombre:'Curitas (caja)',    stock:15, min:4,  unidad:'u' },
      { id:5, nombre:'Termómetros',       stock:8,  min:2,  unidad:'u' },
      { id:6, nombre:'Vitamina C',        stock:20, min:5,  unidad:'u' },
    ],
  },
  {
    slug: 'abarrotes',
    nombre: 'Tienda abarrotes',
    icono: '🛒',
    descripcion: 'Abarrotes, granos y productos básicos',
    color: '#8B5A2B',
    colorDark: '#5a3818',
    colorLight: '#a87040',
    colorCream: '#fdeed0',
    tipo: 'mostrador',
    tabs: ['mostrador','caja','inventario','menu','reportes','admin'],
    mesasCount: 0,
    menu: [
      { id:1, nombre:'Arroz (lb)',      precio:4,  emoji:'🍚', invId:1, unidad:'lb' },
      { id:2, nombre:'Frijol negro (lb)',precio:5, emoji:'🫘', invId:2, unidad:'lb' },
      { id:3, nombre:'Aceite 1L',       precio:35, emoji:'🫙', invId:3, unidad:'u' },
      { id:4, nombre:'Azúcar (lb)',     precio:3,  emoji:'🍬', invId:4, unidad:'lb' },
      { id:5, nombre:'Sal (lb)',        precio:2,  emoji:'🧂', invId:5, unidad:'lb' },
      { id:6, nombre:'Fideos (bolsa)',  precio:8,  emoji:'🍜', invId:6, unidad:'u' },
    ],
    inventario: [
      { id:1, nombre:'Arroz',     stock:50, min:10, unidad:'lb' },
      { id:2, nombre:'Frijol',    stock:40, min:8,  unidad:'lb' },
      { id:3, nombre:'Aceite 1L', stock:15, min:4,  unidad:'u' },
      { id:4, nombre:'Azúcar',    stock:60, min:15, unidad:'lb' },
      { id:5, nombre:'Sal',       stock:30, min:8,  unidad:'lb' },
      { id:6, nombre:'Fideos',    stock:24, min:6,  unidad:'u' },
    ],
  },
  {
    slug: 'minimarket',
    nombre: 'Mini market',
    icono: '🏪',
    descripcion: 'Conveniencia rápida todo el día',
    color: '#2C5F8B',
    colorDark: '#163a5a',
    colorLight: '#4078aa',
    colorCream: '#f0eedd',
    tipo: 'mostrador',
    tabs: ['mostrador','caja','inventario','menu','reportes','admin'],
    mesasCount: 0,
    menu: [
      { id:1, nombre:'Refresco 600ml',  precio:18, emoji:'🥤', invId:1, unidad:'u' },
      { id:2, nombre:'Agua 1.5L',       precio:12, emoji:'💧', invId:2, unidad:'u' },
      { id:3, nombre:'Pan tajado',      precio:22, emoji:'🍞', invId:3, unidad:'u' },
      { id:4, nombre:'Papas fritas',    precio:15, emoji:'🥔', invId:4, unidad:'u' },
      { id:5, nombre:'Chocolate 40g',   precio:10, emoji:'🍫', invId:5, unidad:'u' },
      { id:6, nombre:'Leche 1L',        precio:25, emoji:'🥛', invId:6, unidad:'u' },
    ],
    inventario: [
      { id:1, nombre:'Refrescos 600ml', stock:48, min:12, unidad:'u' },
      { id:2, nombre:'Agua 1.5L',      stock:24, min:6,  unidad:'u' },
      { id:3, nombre:'Pan tajado',     stock:10, min:3,  unidad:'u' },
      { id:4, nombre:'Papas fritas',   stock:30, min:8,  unidad:'u' },
      { id:5, nombre:'Chocolates',     stock:40, min:10, unidad:'u' },
      { id:6, nombre:'Leche 1L',       stock:15, min:4,  unidad:'u' },
    ],
  },
  {
    slug: 'ferreteria',
    nombre: 'Ferretería',
    icono: '🔧',
    descripcion: 'Materiales, herramientas y suministros',
    color: '#5A4A38',
    colorDark: '#2f261c',
    colorLight: '#786050',
    colorCream: '#f5e8c8',
    tipo: 'mostrador',
    tabs: ['mostrador','caja','inventario','menu','reportes','admin'],
    mesasCount: 0,
    menu: [
      { id:1, nombre:'Martillo',            precio:80,  emoji:'🔨', invId:1, unidad:'u' },
      { id:2, nombre:'Tornillos (bolsa)',   precio:25,  emoji:'🔩', invId:2, unidad:'u' },
      { id:3, nombre:'Cinta aislante',      precio:15,  emoji:'🖊️', invId:3, unidad:'u' },
      { id:4, nombre:'Foco LED 9W',         precio:40,  emoji:'💡', invId:4, unidad:'u' },
      { id:5, nombre:'Brocas (juego)',      precio:90,  emoji:'🔧', invId:5, unidad:'u' },
      { id:6, nombre:'Pintura 1 galón',    precio:180, emoji:'🪣', invId:6, unidad:'u' },
    ],
    inventario: [
      { id:1, nombre:'Martillos',          stock:8,  min:2, unidad:'u' },
      { id:2, nombre:'Tornillos (bolsas)', stock:20, min:5, unidad:'u' },
      { id:3, nombre:'Cinta aislante',     stock:25, min:6, unidad:'u' },
      { id:4, nombre:'Focos LED 9W',       stock:30, min:8, unidad:'u' },
      { id:5, nombre:'Brocas (juego)',     stock:10, min:2, unidad:'u' },
      { id:6, nombre:'Pintura galón',      stock:12, min:3, unidad:'u' },
    ],
  },
  {
    slug: 'polleria',
    nombre: 'Pollería',
    icono: '🍗',
    descripcion: 'Pollo al carbón y piezas por unidad',
    color: '#A85A1F',
    colorDark: '#6b3812',
    colorLight: '#c87030',
    colorCream: '#fdf0d8',
    tipo: 'mostrador',
    tabs: ['mostrador','cocina','caja','inventario','menu','reportes','admin'],
    mesasCount: 0,
    menu: [
      { id:1, nombre:'Pollo entero asado',  precio:120, emoji:'🍗', invId:1, unidad:'u' },
      { id:2, nombre:'Medio pollo',         precio:65,  emoji:'🍗', invId:1, unidad:'u' },
      { id:3, nombre:'Cuarto de pollo',     precio:35,  emoji:'🍗', invId:1, unidad:'u' },
      { id:4, nombre:'Pechuga fileteada',   precio:45,  emoji:'🍖', invId:2, unidad:'u' },
      { id:5, nombre:'Tortillas (3 uds)',   precio:10,  emoji:'🫓', invId:3, unidad:'u' },
      { id:6, nombre:'Refresco',            precio:15,  emoji:'🥤', invId:4, unidad:'u' },
    ],
    inventario: [
      { id:1, nombre:'Pollos enteros', stock:15, min:4, unidad:'u' },
      { id:2, nombre:'Pechugas',      stock:10, min:3, unidad:'u' },
      { id:3, nombre:'Tortillas',     stock:8,  min:2, unidad:'paquete' },
      { id:4, nombre:'Refrescos',     stock:24, min:6, unidad:'u' },
    ],
  },

  // ─── TIPO: peso (balanza, decimales, precio×peso) ────────────────────────
  {
    slug: 'carniceria',
    nombre: 'Carnicería',
    icono: '🥩',
    descripcion: 'Venta de carnes por libra y corte',
    color: '#7A1515',
    colorDark: '#4a0a0a',
    colorLight: '#a83a2c',
    colorCream: '#fdf3e8',
    tipo: 'peso',
    tabs: ['mostrador','caja','inventario','menu','reportes','admin'],
    mesasCount: 0,
    menu: [
      { id:1, nombre:'Lomo de res',       precio:35, emoji:'🥩', invId:1, unidad:'lb' },
      { id:2, nombre:'Bistec de res',     precio:30, emoji:'🥩', invId:2, unidad:'lb' },
      { id:3, nombre:'Costilla de cerdo', precio:28, emoji:'🍖', invId:3, unidad:'lb' },
      { id:4, nombre:'Pechuga de pollo',  precio:18, emoji:'🍗', invId:4, unidad:'lb' },
      { id:5, nombre:'Chorizo',           precio:22, emoji:'🌭', invId:5, unidad:'lb' },
      { id:6, nombre:'Res molida',        precio:25, emoji:'🥩', invId:6, unidad:'lb' },
    ],
    inventario: [
      { id:1, nombre:'Lomo de res',       stock:20, min:5, unidad:'lb' },
      { id:2, nombre:'Bistec de res',     stock:15, min:4, unidad:'lb' },
      { id:3, nombre:'Costilla cerdo',    stock:18, min:4, unidad:'lb' },
      { id:4, nombre:'Pechuga pollo',     stock:25, min:6, unidad:'lb' },
      { id:5, nombre:'Chorizo',           stock:10, min:2, unidad:'lb' },
      { id:6, nombre:'Res molida',        stock:12, min:3, unidad:'lb' },
    ],
  },
  {
    slug: 'verduleria',
    nombre: 'Verdulería',
    icono: '🥬',
    descripcion: 'Frutas y verduras por libra o unidad',
    color: '#2D5016',
    colorDark: '#1a3009',
    colorLight: '#426824',
    colorCream: '#f0e8c8',
    tipo: 'peso',
    tabs: ['mostrador','caja','inventario','menu','reportes','admin'],
    mesasCount: 0,
    menu: [
      { id:1, nombre:'Tomate',     precio:4,  emoji:'🍅', invId:1, unidad:'lb' },
      { id:2, nombre:'Cebolla',    precio:3,  emoji:'🧅', invId:2, unidad:'lb' },
      { id:3, nombre:'Papa',       precio:2.50,emoji:'🥔',invId:3, unidad:'lb' },
      { id:4, nombre:'Zanahoria',  precio:3,  emoji:'🥕', invId:4, unidad:'lb' },
      { id:5, nombre:'Lechuga',    precio:8,  emoji:'🥬', invId:5, unidad:'u' },
      { id:6, nombre:'Aguacate',   precio:12, emoji:'🥑', invId:6, unidad:'u' },
      { id:7, nombre:'Limón',      precio:10, emoji:'🍋', invId:7, unidad:'docena' },
    ],
    inventario: [
      { id:1, nombre:'Tomate',    stock:30, min:8,  unidad:'lb' },
      { id:2, nombre:'Cebolla',   stock:25, min:6,  unidad:'lb' },
      { id:3, nombre:'Papa',      stock:50, min:12, unidad:'lb' },
      { id:4, nombre:'Zanahoria', stock:20, min:5,  unidad:'lb' },
      { id:5, nombre:'Lechuga',   stock:15, min:4,  unidad:'u' },
      { id:6, nombre:'Aguacate',  stock:20, min:5,  unidad:'u' },
      { id:7, nombre:'Limón',     stock:10, min:2,  unidad:'docena' },
    ],
  },
  {
    slug: 'tortilleria',
    nombre: 'Tortillería',
    icono: '🌽',
    descripcion: 'Tortillas y masa al peso',
    color: '#A07A15',
    colorDark: '#6b4f0a',
    colorLight: '#c09030',
    colorCream: '#fdf5d0',
    tipo: 'peso',
    tabs: ['mostrador','caja','inventario','menu','reportes','admin'],
    mesasCount: 0,
    menu: [
      { id:1, nombre:'Tortilla de maíz',  precio:5,  emoji:'🫓', invId:1, unidad:'docena' },
      { id:2, nombre:'Tortilla de harina',precio:8,  emoji:'🫓', invId:2, unidad:'docena' },
      { id:3, nombre:'Masa preparada',    precio:4,  emoji:'🌽', invId:3, unidad:'lb' },
      { id:4, nombre:'Tamales (c/u)',     precio:15, emoji:'🫔', invId:4, unidad:'u' },
    ],
    inventario: [
      { id:1, nombre:'Tortilla maíz',   stock:20, min:5,  unidad:'docena' },
      { id:2, nombre:'Tortilla harina', stock:15, min:4,  unidad:'docena' },
      { id:3, nombre:'Masa (lb)',        stock:40, min:10, unidad:'lb' },
      { id:4, nombre:'Tamales',         stock:30, min:8,  unidad:'u' },
    ],
  },
];

// Exportar para Node.js (require) y browser (window)
if (typeof module !== 'undefined' && module.exports) module.exports = RUBROS;
if (typeof window !== 'undefined') window.RUBROS = RUBROS;
